Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechTreeMVCWebApplication.Data;
using TechTreeMVCWebApplication.Entities;

namespace TechTreeMVCWebApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Category
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Admin/Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,ThumbnailImagePath")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,ThumbnailImagePath")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

Controllers/UserAuthController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using TechTreeMVCWebApplication.Data;
using TechTreeMVCWebApplication.Entities;
using TechTreeMVCWebApplication.Models;
using MpesaSdk.Interfaces;

namespace TechTreeMVCWebApplication.Controllers
{
    public class UserAuthController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;
        private readonly IMpesaClient _mpesaService;

        public UserAuthController(ApplicationDbContext context,
                                  UserManager<ApplicationUser> userManager,
                                  SignInManager<ApplicationUser> signInManager,IMpesaClient mpesaService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
            _mpesaService = mpesaService;
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            loginModel.LoginInValid = "true";

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(loginModel.Email,
                                                                     loginModel.Password,
                                                                     loginModel.RememberMe,
                                                                     lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    loginModel.LoginInValid = "";
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt");
                }

            }
            return PartialView("_UserLoginPartial", loginModel);
        
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();

            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }
        
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterUser(RegistrationModel registrationModel)
        {
            registrationModel.RegistrationInValid = "true";

            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser
                {
                    UserName = registrationModel.Email,
                    Email = registrationModel.Email,
                    PhoneNumber = registrationModel.PhoneNumber,
                    FirstName = registrationModel.FirstName,
                    LastName = registrationModel.LastName

                };

                var result = await _userManager.CreateAsync(user, registrationModel.Password);

                if (result.Succeeded)
                {
                    registrationModel.RegistrationInValid = "";

                    await _signInManager.SignInAsync(user, isPersistent: false);

                    if (registrationModel.CategoryId != 0)
                    {
                        await AddCategoryToUser(user.Id, registrationModel.CategoryId);

                    }

                    return PartialView("_UserRegistrationPartial", registrationModel);
                }

                AddErrorsToModelState(result);

            }
            return PartialView("_UserRegistrationPartial", registrationModel);

        }

        [AllowAnonymous]
        public async Task<bool> UserNameExists(string userName)
        {
            bool userNameExists = await _context.Users.AnyAsync(u => u.UserName.ToUpper() == userName.ToUpper());

            if (userNameExists)
                return true;

            return false;

        }

        private void AddErrorsToModelState(IdentityResult result)
        {
            foreach (var error in result.Errors)
                ModelState.AddModelError(string.Empty, error.Description);
        }

        private async Task AddCategoryToUser(string userId, int categoryId)
        {
            UserCategory userCategory = new UserCategory();
            userCategory.CategoryId = categoryId;
            userCategory.UserId = userId;
            _context.UserCategory.Add(userCategory);
            await _context.SaveChangesAsync();
        }  

    }
    
}

Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TechTreeMVCWebApplication.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "admin"))
{
    <li class="nav-item dropdown show">
        <a class="dropdown-toggle nav-link text-dark" href="#" data-toggle="dropdown"><i class="fa-solid fa-gears"></i>Manage</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index"><i class="fas fa-box mr-2"></i>Manage Courses</a>
           
            <a class="dropdown-item" asp-area="Admin" asp-controller="UsersToCategory"><i class="fas fa-users mr-2"></i>Manage User Enrollement</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-area="Admin" asp-controller="MediaType" asp-action="Index"><i class="fas fa-file-video mr-2"></i>Manage Media Types</a>
        </div>
    </li>
}

else if(!SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" href="#Courses"><i class="fas fa-laptop-code mr-1 text-warning"></i>Courses</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#ContactUs"><i class="fas fa-phone-alt mr-1 text-warning"></i>Contact</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#AboutUs"><i class="fas fa-chalkboard-teacher mr-1 text-warning"></i>About</a>
    </li>
}

Views/Shared/_AuthScriptsPartial.cshtml
<script src="~/js/UserRegistration.js" asp-append-version="true"></script>
<script src="~/js/UserLogin.js" asp-append-version="true"></script>
<script src="~/js/donation.js" asp-append-version="true"></script>
<script src="~/js/BootstrapAlerts.js" asp-append-version="true"></script>

Views/Shared/_DashDisplayCardRowPartial.cshtml
@model IEnumerable<Category>

@if (Model.Count() > 0)
{
    <div class="row mt-3">
        @foreach (Category item in Model)
        {
        <div class="col-md-3 mt-3">
            <a href="#" class="CardRegisterLink text-dark" data-categoryId="@item.Id">
                <div class="card">
                    <img class="img-thumbnail" src="@item.ThumbnailImagePath" alt="@item.Title">
                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                        <p class="card-text">@item.Description</p>
                    </div>
                </div>
                
            </a>
            
        </div>
        }
    </div>
}

Views/Shared/_DateScriptsPartial.cshtml
<script src="~/js/DateFunctions.js"></script>
<script src="~/js/DatePicker.js"></script>

Views/Shared/_DefaultHomePageContentPartial.cshtml
@model IEnumerable<Category>
<!--Hero Section-->
<div class="hero section">
    <img class="img-fluid" src="~/Images/hero4.jpg">
    <div class="hero-heading">
        <h2 class="hero-heading-text">Empowering Growth, One skill at time</h2>
        <a id="HeroDonationButton" class="btn btn-outline-warning btn-lg text-light hero-register-button" data-toggle="modal" data-target="#UserRegistrationModal">Get Started</a>
    </div>
</div>

<hr class="section-divider" />

<!--Courses Section-->
<div id="Courses" class="courses section">
    <h3 class="section-header"><i class="fas fa-laptop-code mr-2 text-info"></i>Courses</h3>
    @{ const int itemsPerRow = 4;

        var count = Model.Count() / itemsPerRow;
        var catList = new List<Category>(); }
    @for (int i = 0; i <= count; i++)
    {
        catList = Model.Skip(i * itemsPerRow).Take(itemsPerRow).ToList();

<partial name="_DisplayCardRowPartial" model="catList" />}
</div>

<hr class="section-divider" />

<!--Contact Us Section-->

<div id="ContactUs" class="contact-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-phone-alt mr-2 text-info"></i>Contact Us</h3>
    <div class="col-md-5">
        Email us any questions or inquiries or call +1 643 22 23 456. We would be happy to answer your questions and set up a meeting with you.
    </div>
    <div class="mt-3 row">
        <div class="col col-md-6">
            <form>
                <input type="hidden" />
                <div class="form-group">
                    <label for="Name" class="control-label">Name: </label>
                    <input id="Name" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Email" class="control-label">Email: </label>
                    <input id="Email" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Subject" class="control-label">Subject: </label>
                    <input id="Subject" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="MessageBody" class="control-label">Message: </label>
                    <textarea id="Messagebody" cols="30" rows="10" class="form-control"></textarea>

                </div>
                <div class="form-group d-flex">
                    <input type="button" value="Send Email" class="btn btn-outline-info ml-auto" />
                </div>
            </form>
        </div>

        <div id="map-container-google-1" class="col col-md-6 z-depth-1-half map-container">
            <iframe src="https://maps.google.com/maps?q=waterloo&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0"
                    style="border: 0; height: 100%; width: 100%" allowfullscreen></iframe>
        </div>

    </div>
</div>
<hr class="section-divider" />

<!--About Us Section-->

<div id="AboutUs" class="about-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-chalkboard-teacher mr-2 text-info"></i>About Us</h3>
    <div class="mt-3 row">
        <div class="col col-md-6">
            <p>
                <strong>upSkill Hub</strong> is an online learning platform that offers thousands of free online courses.
            </p>

            <img src="~/Images/olp.png" style="height:50%; width:100%" />

        </div>
        <div class="col col-md-6">

            <h3 class="section-header text-info ml-3"><i class="fa-solid fa-align-center text-info mr-2 "></i>Mission</h3>
            <p>
                Our Mission is to Provide Various Learning Materials to help the learner gain skills in their area of interest.
            </p>

            <h3 class="section-header text-info ml-3"><i class="fas fa-rocket mr-2 text-info"></i>Vision</h3>
            <p>
                Our Vision is to become the number one leading upskilling hub in the world.
            </p>
        </div>
    </div>
</div>

Views/Shared/_DisplayCardRowPartial.cshtml
@model IEnumerable<Category>

@if (Model.Count() > 0)
{
    <div class="row mt-3">
        @foreach (Category item in Model)
        {
        <div class="col-md-3 mt-3">
            <a href="#" class="RegisterLink text-dark" data-categoryId="@item.Id">
                <div class="card">
                    <img class="img-thumbnail" src="@item.ThumbnailImagePath" alt="@item.Title">
                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                        <p class="card-text">@item.Description</p>
                    </div>
                    <a href="#" class="RegisterLink btn btn-outline-info">Enroll</a>
                </div>
                
            </a>
            
        </div>
        }
    </div>
}

Views/Shared/_FooterPartial.cshtml
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom bg-warning">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block text-white">
            <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->
        <!-- Right -->
        <div>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-facebook-f" style="color:white"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-twitter" style="color:white"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-google" style="color:white"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-instagram" style="color:white"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-linkedin" style="color:white"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-github" style="color:white"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->
    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h4 class="text-uppercase fw-bold mb-4 text-dark">
                        <i class="fa-solid fa-graduation-cap"></i>UpSkill Hub
                    </h4>
                    <p>
                        Education is a basic need. Let's all learn and go beyond horizon. Get Unlimited resources at UpSkill Hub
                    </p>
                </div>
                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4 text-info">
                        Popular Courses
                    </h6>
                    <p>
                        <a href="#!" class="text-reset">Software Engineering</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Human Anatomy</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Accounting</a>
                    </p>
                    <p>
                        <a href="#!" class="text-reset">Entrepreneurship</a>
                    </p>
                </div>
                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4 text-info">
                        Partners
                    </h6>
                    <p>
                        <a href="udemy.com" class="text-reset">Udemy</a>
                    </p>
                    <p>
                        <a href="youtube.com" class="text-reset">Youtube</a>
                    </p>
                    <p>
                        <a href="coursera.org" class="text-reset">Coursera</a>
                    </p>
                    <p>
                        <a href="edx.org" class="text-reset">Edx</a>
                    </p>
                </div>
                <!-- Grid column -->
                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4 text-info">
                        Contact
                    </h6>
                    <p><i class="fas fa-home me-3"></i> Waterloo, ON</p>
                    <p>
                        <i class="fas fa-envelope me-3"></i>
                        info@upskillhub.com
                    </p>
                    <p><i class="fas fa-phone me-3"></i> +1 643 22 23 456</p>
                    <p><i class="fas fa-print me-3"></i> +1 543 72 14 367</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->
    <!-- Copyright -->
    <div class="text-center p-4 bg-warning text-white">
        © 2024 Copyright:
        <a class="text-reset fw-bold">UpSkill Hub </a> All Rights Reserved
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->

Views/Shared/_UserLoginPartial.cshtml
@model TechTreeMVCWebApplication.Models.LoginModel 

   <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <h5 class="modal-title text-white" id="exampleModalLabel"><i class="fas fa-sign-in-alt mr-1 text-white"></i> Sign In </h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="alert_placeholder_login">
                </div>
                <form id="UserLoginForm" asp-controller="UserAuth" asp-action="Login">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="LoginInValid">
                    <div class="form-group row">                        
                        <label asp-for="Email" class="col-md-4 col-form-label "></label>
                        <div class="col-md-8">
                            <input asp-for="Email" placeholder="Email Address" class="form-control">
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Password" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Password" placeholder="Password" class="form-control">
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group-row">
                        <div class="col-md-8 offset-md-4">
                            <div class="form-check">
                                <input asp-for="RememberMe" class="form-check-input">
                                <label asp-for="RememberMe" class="form-check-label"></label>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="login" name="login" class="btn btn-warning text-white">Login</button>
            </div>
        </div>
    </div>

Views/Shared/_UserRegistrationPartial.cshtml
    @model TechTreeMVCWebApplication.Models.RegistrationModel

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <h5 class="modal-title text-white" id="exampleModalLabel"><i class="fas fa-user mr-2 text-white"></i> Create Account</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="alert_placeholder_register">
                </div>
                <form id="UserRegistrationForm" name="UserRegistrationForm" asp-controller="UserAuth" asp-action="RegisterUser">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="RegistrationInValid">

                    <div class="form-group row">
                        <label asp-for="FirstName" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="FirstName" placeholder="First Name" class="form-control">
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="LastName" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="LastName" placeholder="Last Name" class="form-control">
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Email" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Email" placeholder="Email Address" class="form-control">
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="PhoneNumber" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="PhoneNumber" placeholder="Phone Number" class="form-control">
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Password" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Password" placeholder="Password" class="form-control">
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="ConfirmPassword" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="ConfirmPassword" placeholder="Confirm Password" class="form-control">
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-8">
                            <div class="form-check">
                                <input asp-for="AcceptUserAgreement" class="form-check-input">
                                <label asp-for="AcceptUserAgreement" class="form-check-label">I accept the <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a></label>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" asp-for="CategoryId" />
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="register" name="register" type="button" class="btn btn-warning text-white">Register</button>
            </div>
        </div>
    </div>